### ISSUE TITLE
problems installing 

### ISSUE THREAD

**Issue by cmungall** [stevencox/greentranslator#2]
@realmarcin and I are trying to run GreenTeamQ2_Molecular_Targets_Pathways_PM2.5_Ozone.ipynb

```
$ pyvenv venv
$ source venv/bin/activate
$ pip install -r green-requirements.txt 
...
Requirement already satisfied (use --upgrade to upgrade): greentranslator==0.14 in ./venv/lib/python3.5/site-packages (from -r green-requirements.txt (line 2))
...
```

however,

```
$ python
Python 3.5.2 (default, Dec 15 2016, 19:36:04) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from greentranslator.api import GreenTranslator
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cjm/repos/cq-notebooks/venv/lib/python3.5/site-packages/greentranslator/__init__.py", line 1, in <module>
    from greentranslator import api
  File "/Users/cjm/repos/cq-notebooks/venv/lib/python3.5/site-packages/greentranslator/api.py", line 5, in <module>
    import swagger_client
ImportError: No module named 'swagger_client'
>>> 
```

I can't see any swagger_client

my suspicion is that in a previous version you used the swagger-codegen defaults, this was then changed, but the pypi module this is still lingering...

**Comment by cmungall** [comment]
aha, I think our problems will be solved if we use the github version, in the github version this is commented out:

```
#from .swagger_client import DefaultApi
#from .swagger_client.rest import ApiException
```

so maybe a new release to pypi is what is required, thanks!

**Comment by cmungall** [comment]
sorry for the long running chatter; maybe slack is better for this...

we're also trying
```
(venv) ~/repos/cq-notebooks(master) $ pip install git+git://github.com/stevencox/greentranslator.git
```

But get:

```
Collecting git+git://github.com/stevencox/greentranslator.git
  Cloning git://github.com/stevencox/greentranslator.git to /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-8azsul90-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-8azsul90-build/setup.py'
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/ty/0g0s9ngs421_fn4mfsthqnxr0000gn/T/pip-8azsul90-build/
```

I suspect this is to do with the top level 'src' folder in this repo, which seems unusual for python?

I can get everything working if I

 * git clone greentranslator
 * cd src && pip3 install -e .
 * cd back to cq-notebooks
 * rm -rf venv/lib/python3.5/site-packages/greentranslator

**Comment by stevencox** [comment]
?The library's in some flux at the moment so the improvised steps below are the best I've got to offer just now.


But I hope to get a new version out soon and will post that to slack when it's available.


Steve


________________________________
